config/routes.rb
PassingPedagogy::Application.routes.draw do
  get 'in_general', to: 'pages#in_general'
  get 'exercise_1', to: 'pages#exercise_1'
  get 'exercise_2', to: 'pages#exercise_2'
  get 'exercise_3', to: 'pages#exercise_3'
  get 'thanks',     to: 'pages#thanks'
  get 'about',      to: 'pages#about'
  get 'resources',  to: 'pages#resources'

  root to: 'pages#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def tab(action, title = action.to_s.titleize)
    html_class = []


    if controller.action_name == action.to_s
      html_class << 'active'
    end

    content_tag :dd, :class => html_class do
      link_to title, action: action
    end
  end
end

app/views/application/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1309955-16', 'passingpedagogy.com');
  ga('send', 'pageview');

</script>

app/views/application/_footer.html.erb
<footer class="row">
  <div class="twelve columns">
    <hr />
    <div class="row">
      <div class="six columns">

      </div>
      <div class="six columns">
        <ul class="link-list right">
          <li><%= link_to 'Other Resources', resources_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <li><%= link_to 'Thanks', thanks_path %></li>
        </ul>

      </div>
    </div>
  </div>
</footer>

app/views/application/_header.html.erb
<div class="row">
  <div class="twelve columns">
    <div class="panel">
      <h1>Passing Pedagogy</h1>
    </div>
  </div>

  <div class="six columns">
    <p>
      <span class="secondary label">Pass&bull;ing</span>
      The act of juggling between more than one person.
    </p>
  </div>
  <div class="six columns">
    <p>
      <span class="secondary label">Ped&bull;a&bull;go&bull;gy</span>
      The method and practice of teaching.
    </p>
  </div>
</div>

app/views/application/_javascripts.html.erb
<%#= javascript_include_tag 'http://code.jquery.com/jquery-1.8.1.min.js',  %>
<%= javascript_include_tag 'application' %>
<%= yield :javascript %>
<%= render 'analytics' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Passing Pedagogy</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'header' %>

  <div class="row">
    <div class="nine columns push-three">
      <ul class="tabs-content">
        <%= yield %>
      </ul>
    </div>
    <%= render 'nav' %>
  </div>
  <%= render 'footer' %>
  <%= render 'javascripts' %>
</body>
</html>

app/views/pages/_nav.html.erb
<div class="three columns pull-nine">

  <dl class="nice vertical tabs">
    <%= tab :index, 'What is this?' %>
    <%= tab :in_general %>
    <%= tab :exercise_1 %>
    <%= tab :exercise_2 %>
    <%= tab :exercise_3 %>
  </dl>

</div>

app/views/pages/about.html.erb
<li class="active">
  <h4>About Passing Pedagogy</h4>

  <p>Comming Soon!</p>
</li>

app/views/pages/exercise_1.html.erb
<li class="active">
  <h4>Exercise 1</h4>
  <div class="row">
    <div class="seven columns">
      <p>
        The first exercise is 3 club ultimates. Lofty singles, just throw to the empty hand. Only one throw at a time. This one is to learn the basic pass with each hand.
      </p>
    </div>
    <div class="five columns">
      <%= image_tag 'exercise1a.gif' %>
    </div>
  </div>

  <h4>Exercise 1b</h4>
  <div class="row">
    <div class="seven columns">
      <p>
        3 clubs, student starts with two, teacher throws first pass, student learns to react with a pass. This exercise is mostly about timing, and continuing to throw good passes while having another club come in.
      </p>
      <!-- <a href="#exercise_2" class="medium secondary button right">Next &raquo;</a> -->
    </div>
    <div class="five columns">
      <%= image_tag 'exercise1b.gif' %>
    </div>
  </div>
</li>

app/views/pages/exercise_2.html.erb
<li class="active">
  <!-- Exercise 2 could probably be explained better. If I didn't know what was going on, I'd probably have to spend some time trying to work it out. -->

  <h4>Exercise 2</h4>
  <div class="row">
    <div class="seven columns">
      <p>
        Exercise 2: 4 clubs. This is the first 4 throws of 5 ultimates; this is easier than 5 club ultimates because there is a pause. One club starts in each hand. There are four possible starts (one from each hand), and I find that because it can be confusing to switch between them, this exercise works well focusing on each start at a time. Begin with the student starting, and have them switch to the other side as soon as they feel comfortable with the first. Instruct them to start on either side until they are comfortable with both. (note: as the teacher, reacting to either side in this exercise can be mildly confusing at first. It's not hard, just make sure to try it a few times so you know what's up).
      </p>
    </div>
    <div class="five columns">
      <%= image_tag 'exercise2a.gif' %>
    </div>
  </div>

  <h4>Exercise 2b</h4>
  <div class="row">
    <div class="seven columns">
      <p>
        Exercise 2b: same as before, but now with the teacher starting. Stick to one side at a time, and let the student know before switching. Move on when you can consistently catch all four throws from both sides. Review exercise 1b if you think it might be helpful.
      </p>
    </div>
  </div>

  <h4>Exercise 2c</h4>
  <div class="row">
    <div class="seven columns">
      <p>
        Exercise 2c: 4 clubs, same pattern, always start with the same club. This basically cycles through all four starts.
      </p>
    </div>
    <div class="five columns">
      <%= image_tag 'exercise2c.gif' %>
    </div>
  </div>

</li>

app/views/pages/exercise_3.html.erb
<li class="active">
  <h4>Exercise 3</h4>
  <div class="row">
    <div class="seven columns">
      <p>
        Exercise 3: 5 club ultimates. This is passing!
      </p>
    </div>
    <div class="five columns">
      <%= image_tag 'onecount5.gif' %>
    </div>
  </div>
</li>

app/views/pages/in_general.html.erb
<li class="active">
  <h4>General Notes</h4>
  <p>
    In all of these exercises: the teacher crosses, and the student passes straight (the animations are from the teachers point of view).
  </p>
  <p>
    At each step, especially the first, give feedback on passes, focussing on what works, and one thing to change to improve that throw. If passes get rough, go back to the previous exercise to solidify muscle memory.
  </p>
  <p>
    In general, if a step is difficult for the student, you can just work on one side for a while, but don't move on to the next step until both sides are proficient.
  </p>
</li>

app/views/pages/index.html.erb
<li class="active">
  <h4>What is this?</h4>

  <p>
    This site exists to explain in detail a new way to teach passing.
  </p>

  <p>
    If you want to teach a friend to pass, then you've come to the right place.
    If you want to learn to pass, I highly recommend you find someone that already knows how.
    However, this method will also work for two beginners wanting to learn together.
  </p>

  <p>
    I generally teach with this with clubs, but the steps will work well with rings or balls or whatever.
    To learn with this method, it is not necessary for the student to be able to juggle 3 objects,
    although it helps if they have some experience tossing clubs around (or whatever object you are using).
  </p>

</li>

app/views/pages/resources.html.erb
<li class="active">
  <h4>Other Resources</h4>

  <p>Here are some other websites with information about teaching or learning passing:</p>

  <ul>
    <li>
      <a href="http://gnerds.com/juggle/passing.uplift.html">Uplifting Passers</a>
    </li>
  </ul>
</li>

app/views/pages/thanks.html.erb
<li class="active">
  <h2>To give credit, where it's due</h2>

  <p>
    Thanks to Aidan Burns for making the animations and to everyone else who has given feedback about this process. Thanks to Doug Martin, who has been through the workshop many times and helped me improve it. And a special thanks to Hallie McGee who has helped me with every step.
  </p>

</li>